    -- 0
    -- DROP TABLE IF EXISTS `EUREKA_USER`;
    CREATE TABLE `EUREKA_USER` (
          `ID` VARCHAR(16) NOT NULL COMMENT 'ID',
          `USER_NO` VARCHAR(16) NOT NULL COMMENT '用户ID',
          `USER_NAME` VARCHAR(64) NOT NULL COMMENT '用户名',
          `SHORT_NAME` VARCHAR(64) NOT NULL COMMENT '账号名',
          `PASSWORD` VARCHAR(64) NOT NULL COMMENT '账号密码',
          `TELEPHONE` VARCHAR(32)  NULL COMMENT '手机号',
          `QQ_CODE` VARCHAR(32)  NULL COMMENT 'QQ号',
          `GENDER` VARCHAR(16)  NULL COMMENT '性别1-男0-女',
          `CREATE_TIME` TIMESTAMP(0) NOT NULL COMMENT '创建时间'
    );


