spring:
  profiles:
    active: dev
  application:
    name: eureka-user
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
eureka:
  client:
    serviceUrl:
      defaultZone: http://49.235.247.57:1001/eureka/
mybatis:
  configuration:
    database-id: mysql
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://rm-uf6fsblm233b84l15xo.mysql.rds.aliyuncs.com:3306/egov?characterEncoding=utf8&useSSL=false
    useSSL: false
    username: admin123
    password: admin123
server:
  port: 12001
logging:
  level:
    com.rongji.egov: debug
